// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrqBUznQdblVnhm6ThTMpmu-E1-i5fnnU',
    appId: '1:580480626582:web:3b4125847ad310ca8ef7b7',
    messagingSenderId: '580480626582',
    projectId: 'fir-workshop-72894',
    authDomain: 'fir-workshop-72894.firebaseapp.com',
    storageBucket: 'fir-workshop-72894.appspot.com',
    measurementId: 'G-F1H2T8KVWM',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrqBUznQdblVnhm6ThTMpmu-E1-i5fnnU',
    appId: '1:580480626582:web:1a5207ce8f03a4898ef7b7',
    messagingSenderId: '580480626582',
    projectId: 'fir-workshop-72894',
    authDomain: 'fir-workshop-72894.firebaseapp.com',
    storageBucket: 'fir-workshop-72894.appspot.com',
    measurementId: 'G-9N3C97EJL4',
  );
}
